### ISSUE TITLE
Pharo release? Dependencies...

### ISSUE THREAD

**Issue by GrahamMcLeod** [mumez/SCypherGraph#17]
Hi.
I am very keen to try this library. I tried loading in Pharo8/64bit and in Pharo7/64 bit. 
Both failed with:

> This package depends on the following classes:
>   FFIEnumeration
> You must resolve these dependencies before you will be able to load these definitions: 
>   SbBoltType
>   SbBoltType>>#boolean
>   SbBoltType>>#bytes
>   SbBoltType>>#dictionary
>   SbBoltType>>#enumDecl
>   SbBoltType>>#float
>   SbBoltType>>#integer
>   SbBoltType>>#list
>   SbBoltType>>#null
>   SbBoltType>>#string
>   SbBoltType>>#structure
>   SbBoltType>>#isComposite
>   SbBoltType>>#isPrimitive
>   SbBoltType>>#typeSymbol
> 
> 
> Select Proceed to continue, or close this window to cancel the operation.

Can you please advise either/both:
a) Which version of Pharo is required
b) How to overcome this dependency?

I examined both FFI and UFFI but did not find it in either. 
Help would be much appreciated. 

Thanks
Graham - graham@inspired.org

**Comment by mumez** [comment]
Hi Graham ,

SCypherGraph supports Pharo 8 or 9, so you should be able to install it on Pharo 8.
SmallBolt (underlying library) depends on FFIEnumeration, and it does not exist in Pharo 7. 
I should have noted the supporting versions in README.md. I'll update it soon.

There is also a Docker image to demonstrate SCypherGraph.
https://github.com/mumez/scyphergraph-vnc-supervisor
So, if you're using Docker, you can just pull and run the image, or build it by yourself.

Best regards,

**Comment by mumez** [comment]
Updated README
https://github.com/mumez/SCypherGraph/commit/9c73161b0f9fc3997ea7e3c39953a9328fe4a47f

If you still have a problem, please reopen the issue.
