### ISSUE TITLE
Installed in Pharo, Neo4J setup OK, but SbSeabolt fails to find external library

### ISSUE THREAD

**Issue by GrahamMcLeod** [mumez/SCypherGraph#19]
Installed Neo4j happily on macOS Big Sur. Can run the Neo Desktop client OK. 
Installed SCypherGraph OK in Pharo 9 64 bit. No errors. 
Tried to run the db connection check:
   db:=SgGraphDb new. 
   db settings username: 'neo4j'; password: 'neoneo'.
   db allLabels
Returns Error: External Module not found
Please note: I am only fleetingly familiar with FFI!

I checked to see what it is trying to invoke. Seems to be libseabolt17.dylib
Checked where this is located. It is found in the Pharo image path. 
Checked that it is a correct 64 bit dll file and it seems to be. 

Tried various other avenues, but now stumped. Any help appreciated!
State of system in image below:
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/538943/119377295-3e993180-bcbd-11eb-85a5-aa4b82b3bb1c.png">

**Comment by mumez** [comment]
Usually FFI searches the current directory where Pharo image is located. 
But if you failed, try putting 'libseabolt17.dylib' to vm plugins directory ('pharo-vm/Pharo.app/Contents/MacOS/Plugins/').

After you put the file, please restart Pharo. Now SCypherGraph should work.

You can also confirm the loaded plugins by: 
```
Smalltalk vm listLoadedModules
```
It will return the list including 'libseabolt17.dylib'.
